# Generated by Django 6.1.1 on 2026-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price_mean', models.FloatField()),
                ('price_min', models.FloatField()),
                ('price_max', models.FloatField()),
                ('price_sample_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='stations_st_latitud_ba98b4_idx')],
            },
        ),
    ]
